const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),mode=['practice','expansion','checkpoint','pc'].includes(params.get('mode'))?params.get('mode'):'practice',course=ACTIVITIES[mode];let queue=[],at=0,records=[],record,selected=null,picked=[],bank=[],locked=false,retryQueue=[];
const types={choice:'의미와 관계 선택',order:'눌러서 문장 조립',write:'직접 입력',speak:'직접 말하기 · 자기 확인'};
function view(id){['home','work','result'].forEach(k=>$(k).classList.toggle('hidden',k!==id));document.querySelectorAll('audio').forEach(a=>a.pause());window.scrollTo(0,0);}
function start(list){queue=list;at=0;records=[];view('work');show();}
function current(){const {u,q}=queue[at];return course.units[u].questions[q]}
function button(text,fn,cls){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;return b;}
function support(){record.help=true;}
function stopAudio(){document.querySelectorAll('audio').forEach(a=>a.pause())}
function audio(id){const a=document.createElement('audio');a.controls=true;a.preload='none';a.src=`audio/${id}.wav`;a.onplay=()=>document.querySelectorAll('audio').forEach(x=>{if(x!==a)x.pause()});a.onerror=()=>{$('feedback').textContent='음성을 불러오지 못했어요. audio 폴더를 확인해 주세요.'};return a;}
function feedback(text,good=false){$('feedback').textContent=text;$('feedback').className=good?'good':'again'}
function show(){stopAudio();const ref=queue[at],q=current(),unit=course.units[ref.u];record={...ref,help:false,attempts:0,status:'pending'};locked=false;selected=null;picked=[];$('counter').textContent=`${at+1} / ${queue.length}`;$('progressBar').max=queue.length;$('progressBar').value=at;$('kind').textContent=unit.name+' · '+types[q.type];$('prompt').textContent=q.prompt;$('feedback').textContent='';$('feedback').className='';$('response').replaceChildren();$('listen').replaceChildren();['hintText','original','model','nextQ'].forEach(k=>$(k).classList.add('hidden'));$('check').classList.toggle('hidden',q.type==='speak');$('return').href='index.html#page='+unit.page;$('originalImage').src=`assets/page-${unit.page}.png`;$('hint').disabled=false;$('example').disabled=false;document.querySelector('.helpers').classList.toggle('hidden',mode==='checkpoint');
if(q.audio&&q.type!=='speak')$('listen').append(audio(q.audio));
if(q.type==='choice'){const box=document.createElement('div');box.className='choices';q.options.forEach((t,i)=>{const b=button(t,()=>{if(locked)return;selected=i;box.querySelectorAll('button').forEach((x,j)=>x.classList.toggle('selected',i===j));},'option');box.append(b)});$('response').append(box)}
if(q.type==='order'){bank=q.sentence.split(' ').map((word,i)=>({word,i})).sort(()=>Math.random()-.5);if(bank.map(x=>x.word).join(' ')===q.sentence)bank.reverse();drawOrder()}
if(q.type==='write'){const t=document.createElement('textarea');t.id='typed';t.lang='en';t.autocomplete='off';t.spellcheck=false;t.setAttribute('aria-label','영어 답 입력');t.placeholder='영어로 입력하세요';$('response').append(t)}
if(q.type==='speak'){$('response').innerHTML='<div class="speak">먼저 소리 내어 말해 보세요.<br>말한 뒤 ‘예문 확인’을 눌러 비교하세요.<br><small>마이크 녹음·음성 채점은 하지 않아요.</small></div>'}
}
function drawOrder(){const box=document.createElement('div');box.className='answerbox';box.setAttribute('aria-label','조립한 문장');picked.forEach((id,j)=>box.append(button(bank[id].word,()=>{if(locked)return;picked.splice(j,1);drawOrder()},'token')));const tokens=document.createElement('div');tokens.className='tokens';bank.forEach((t,i)=>{const b=button(t.word,()=>{if(locked)return;picked.push(i);drawOrder()},'token');b.disabled=picked.includes(i);tokens.append(b)});$('response').replaceChildren(box,tokens);}
function finish(status){if(locked)return;record.status=status;records.push({...record});locked=true;$('check').classList.add('hidden');$('nextQ').classList.remove('hidden');$('nextQ').textContent=at===queue.length-1?'결과 확인 →':'다음 문제 →';$('hint').disabled=true;$('example').disabled=true;}
function check(){if(locked)return;const q=current();let value,correct;if(q.type==='choice'){if(selected===null){feedback('답을 하나 선택해 주세요.');return}correct=selected===q.answer}else{value=q.type==='order'?picked.map(i=>bank[i].word).join(' '):$('typed').value;if(!value.trim()){feedback('먼저 답을 만들어 주세요.');return}correct=(q.type==='order'?[q.sentence]:q.answers).some(a=>normalizeAnswer(a)===normalizeAnswer(value))}record.attempts++;if(mode==='checkpoint'&&!correct){feedback('이번 답은 기준 답과 달라요. '+q.why);finish('review');return}if(correct){feedback((record.help||record.attempts>1?'다시 확인해서 완성했어요. ':'도움 없이 맞혔어요. ')+q.why,true);finish(record.help||record.attempts>1?'supported':'independent')}else{feedback((q.type==='write'?'준비된 답과 달라요. 이 문제에서 요청한 단어나 구조를 확인해 주세요. 다른 맞는 표현일 가능성은 예문과 비교해 주세요.':'한 번 더 관계를 살펴보세요. ')+ ' 막히면 힌트를 눌러보세요.');}}
function reveal(){if(locked)return;support();const q=current();$('model').replaceChildren();const b=document.createElement('b');b.textContent=q.model||q.sentence||(q.answers?q.answers[0]:q.options[q.answer]);$('model').append(b);const p=document.createElement('p');p.textContent=q.ko||q.why;$('model').append(p);if(q.type==='speak'){if(q.audio)$('model').append(audio(q.audio));const actions=document.createElement('div');actions.className='self';actions.append(button('다시 말해봤어요',()=>{feedback('자기 확인으로 기록했어요. 새 상황에서도 다시 사용해 보세요.',true);finish('self')},'primary'),button('조금 더 연습할래요',()=>{feedback('말하기 복습 대상으로 남겨둘게요.');finish('self-review')},'toggle'));$('model').append(button('예문 가리고 다시 말하기',()=>{b.classList.toggle('hidden');p.classList.toggle('hidden')},'toggle'),actions)}else{const note=document.createElement('p');note.textContent='예문을 확인한 문제는 도움을 받은 것으로 기록해요.';$('model').append(note)}$('model').classList.remove('hidden');}
function results(){view('result');const count=s=>records.filter(r=>r.status===s).length;retryQueue=records.filter(r=>r.status!=='independent'&&r.status!=='self').map(({u,q})=>({u,q}));$('report').innerHTML=`<p class="score">도움 없이 확인 ${count('independent')}문항<br>도움·재시도 후 확인 ${count('supported')}문항<br>다시 확인할 문항 ${count('review')}개<br>건너뛴 문항 ${count('skip')}개<br>말하기 자기 확인 ${count('self')+count('self-review')}개</p>`;$('recommendations').replaceChildren();const weak=[...new Set(retryQueue.map(r=>r.u))];if(mode==='checkpoint'){const full=records.length===8;const n=count('independent');const advice=document.createElement('p');advice.className='help';advice.textContent=!full?'일부 문항을 다시 확인했어요. 전체 점검으로 새 상황에서도 확인해 보세요.':n===8?'이번 8문항은 도움 없이 확인했어요. PC 심화는 선택하고, 본문 진도를 이어가도 좋아요.':n>=6?'대부분 확인했어요. 아래에 표시된 부분을 복습한 뒤 이어가기를 권해요.':'관계와 문장 만들기를 조금 더 익혀보세요. 아래 설명과 연습을 추천해요.';$('report').append(advice);}if(!weak.length){const p=document.createElement('p');p.textContent='이번 문항은 확인했어요. 다른 상황에 적용하거나 본문 진도를 이어가 보세요.';$('recommendations').append(p)}weak.forEach(u=>{const div=document.createElement('div');div.className='rec';const title=document.createElement('strong');title.textContent=course.units[u].name;const p=document.createElement('p');p.textContent='도움·재시도·건너뛰기 또는 말하기 복습 요청이 있었어요.';const a=document.createElement('a');a.href='index.html#page='+course.units[u].page;a.textContent='관련 설명 확인 →';div.append(title,p,a,document.createElement('br'),button('이 활동을 새로 연습',()=>start(course.units[u].questions.map((_,q)=>({u,q}))),'textbutton'));$('recommendations').append(div)});const link=document.createElement('a');link.className='bookbutton';link.style.display='block';link.style.marginTop='24px';link.href=mode==='practice'?'activity.html?mode=expansion':mode==='expansion'?'activity.html?mode=checkpoint':'finish.html';link.textContent=mode==='practice'?'다른 동사와 문장으로 확장 →':mode==='expansion'?'마무리 점검으로 →':'단원 마무리 · 다음 진도 안내 →';$('recommendations').append(link);$('retry').classList.toggle('hidden',!retryQueue.length);}
$('title').textContent=course.title;$('intro').textContent=course.subtitle;document.querySelectorAll('.modes a').forEach(a=>a.classList.toggle('active',a.href.includes('mode='+mode)));course.units.forEach((u,i)=>{const b=button('',()=>start(u.questions.map((_,q)=>({u:i,q}))),'unit');b.innerHTML=`<span>0${i+1} · ${u.questions.length}문항</span>${u.name}`;$('units').append(b)});$('diagnose').onclick=()=>start(mode==='checkpoint'?course.units.flatMap((unit,u)=>unit.questions.map((_,q)=>({u,q}))):course.units.map((_,u)=>({u,q:0})));if(mode==='checkpoint'||mode==='pc'){document.querySelector('.quick h2').textContent=mode==='checkpoint'?'이번 단원의 마무리 점검':'원하는 활동을 골라도 좋아요';document.querySelector('.quick p').textContent=mode==='checkpoint'?'8문항 · 힌트 없이 첫 응답을 확인해요. 8개 확인은 다음 진도 권장, 6~7개는 일부 복습, 5개 이하는 보강을 권해요. 학습용 임시 기준이며 이동을 막지 않아요.':'비교·조립·타이핑을 한 문제씩 먼저 만나거나 아래에서 골라보세요. 작은 화면에서도 사용할 수 있어요.';$('diagnose').textContent=mode==='checkpoint'?'8문항 점검 시작 →':'세 가지 활동 맛보기 →';}$('menu').onclick=()=>view('home');$('finish').onclick=()=>view('home');$('check').onclick=check;$('hint').onclick=()=>{support();$('hintText').textContent=current().hint;$('hintText').classList.remove('hidden')};$('shape').onclick=()=>{if(!locked)support();$('original').classList.toggle('hidden')};$('hideOriginal').onclick=()=>$('original').classList.add('hidden');$('example').onclick=reveal;$('skip').onclick=()=>{if(!locked)finish('skip');advance()};function advance(){stopAudio();if(++at<queue.length){show();window.scrollTo(0,0)}else results()};$('nextQ').onclick=advance;$('retry').onclick=()=>start([...retryQueue]);window.addEventListener('pagehide',stopAudio);const u=Number(params.get('unit'));if(params.has('unit')&&Number.isInteger(u)&&u>=0&&u<course.units.length)start(course.units[u].questions.map((_,q)=>({u,q})));else view('home');
